SELECT
    a.CAR_ID,
    a.CAR_TYPE,
    ROUND(a.DAILY_FEE*30*(100-C.DISCOUNT_RATE)/100, 0) FEE
FROM CAR_RENTAL_COMPANY_CAR a
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b
    ON a.CAR_ID = b.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c
    ON a.CAR_TYPE = c.CAR_TYPE
    WHERE a.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE < '2022-12-01' AND END_DATE > '2022-11-01'
        ) AND c.DURATION_TYPE = '30일 이상'
GROUP BY 1
HAVING a.CAR_TYPE IN ('세단', 'SUV')
    AND (FEE >= 500000 AND FEE < 2000000)
ORDER BY 3 DESC, 2 ASC, 1 DESC;