SELECT
    SUBSTR(os.SALES_DATE, 1, 4) YEAR,
    SUBSTR(os.SALES_DATE, 6, 2) MONTH,
    ui.GENDER,
    COUNT(DISTINCT os.USER_ID) USERS
FROM USER_INFO ui
    JOIN ONLINE_SALE os
    ON ui.USER_ID = os.USER_ID
    WHERE ui.GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3 ASC;