SELECT
    b.HISTORY_ID,
    ROUND(a.DAILY_FEE * (DATEDIFF(b.END_DATE, b.START_DATE) +1) * (
    CASE
        WHEN DATEDIFF(b.END_DATE, b.START_DATE) + 1 >= 90 THEN 0.85
        WHEN DATEDIFF(b.END_DATE, b.START_DATE) + 1 >= 30 THEN 0.92
        WHEN DATEDIFF(b.END_DATE, b.START_DATE) + 1 >= 7 THEN 0.95
        ELSE 1 END)) FEE
FROM CAR_RENTAL_COMPANY_CAR a
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b
    ON a.CAR_ID = b.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c
    ON a.CAR_TYPE = c.CAR_TYPE
    WHERE a.CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY 2 DESC, 1 DESC;