SELECT
    CONCAT('/home/grep/src/', ugf.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) FILE_PATH
FROM USED_GOODS_BOARD ugb
    JOIN USED_GOODS_FILE ugf
    ON ugb.BOARD_ID = ugf.BOARD_ID
WHERE VIEWS IN (SELECT MAX(VIEWS) VIEWS FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC